// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    AMenu: typeof import("@arco-design/web-vue")["Menu"];
    AMenuItem: typeof import("@arco-design/web-vue")["MenuItem"];
    ASubMenu: typeof import("@arco-design/web-vue")["SubMenu"];
    CustomLayout: typeof import("./src/packages/components/custom-layout/index.vue")["default"];
    SvgIcon: typeof import("./src/packages/components/svg-icon/index.vue")["default"];
  }
}

export {};
